- name: Fetch Prices and Update Badge
  run: |
    mkdir -p badges

    BTC=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd" | jq -r '.bitcoin.usd')
    ETC=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=ethereum-classic&vs_currencies=usd" | jq -r '.["ethereum-classic"].usd')

    echo '{
      "schemaVersion": 1,
      "label": "BTC",
      "message": "'"${BTC} USD"'",
      "color": "orange"
    }' > badges/btc-badge.json

    echo '{
      "schemaVersion": 1,
      "label": "ETC",
      "message": "'"${ETC} USD"'",
      "color": "green"
    }' > badges/etc-badge.json
